# permissions for end users to edit microk8sconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: microk8sconfig-editor-role
rules:
- apiGroups:
  - bootstrap.cluster.x-k8s.io
  resources:
  - microk8sconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bootstrap.cluster.x-k8s.io
  resources:
  - microk8sconfigs/status
  verbs:
  - get
