apiVersion: cluster.x-k8s.io/v1alpha2
kind: Cluster
metadata:
  name: capdo-microk8s
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: DOCluster
    name: capdo-microk8s
    namespace: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: DOCluster
metadata:
  name: capdo-microk8s
  namespace: default
spec:
  region: sgp1
  network:
    apiServerLoadbalancers: 
      port: 16443