apiVersion: bootstrap.cluster.x-k8s.io/v1alpha1
kind: Microk8sConfigTemplate
metadata:
  name: capdo-microk8s-worker-0
spec:
  template:
    spec:
      # Add fields here
      token: abc.123488779
      channel: 1.17/stable
      controlPlaneHost: 128.199.128.28
---
apiVersion: cluster.x-k8s.io/v1alpha2
kind: MachineDeployment
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: capdo-microk8s
    nodepool: nodepool-0
  name: capdo-microk8s-md-0
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: capdo-microk8s
      nodepool: nodepool-0
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: capdo-microk8s
        nodepool: nodepool-0
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha1
          kind: Microk8sConfigTemplate
          name: capdo-microk8s-worker-0
          namespace: default
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
        kind: DOMachineTemplate
        name: capdo-microk8s-md-0
        namespace: default
      version: v1.16.2
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: DOMachineTemplate
metadata:
  name: capdo-microk8s-md-0
  namespace: default
spec:
  template:
    spec:
      image: 61310770
      size: s-2vcpu-2gb
      sshKeys:
      - 77:45:be:8b:e9:38:8e:04:55:d5:71:5b:3c:c6:68:57
